### ISSUE TITLE
Default to fallback mode

### ISSUE THREAD

**Issue by carlosjeurissen** [Hypnosphi/postcss-overflow-clip#1]
Wonderful package, thanks for making this!

To make sure it doesn't break any current sites, I think it's best to not automatically add `clip` when `hidden` is found in the code, and only add the fallback to clip. The other use-case could then be enabled with an option.

**Comment by Hypnosphi** [comment]
It makes sense, PR is welcome

**Comment by carlosjeurissen** [comment]
@Hypnosphi See https://github.com/Hypnosphi/postcss-overflow-clip/pull/2

We might want to rename the master branch to main as well.

**Comment by carlosjeurissen** [comment]
Closed by #5
