### ISSUE TITLE
Support overflow-x and overflow-y

### ISSUE THREAD

**Issue by carlosjeurissen** [Hypnosphi/postcss-overflow-clip#3]
At some point we will want to support these properties as well. Tho we should make sure no possible conflict is there with other overflow properties.

**Comment by Hypnosphi** [comment]
Makes sense. I don't actually use this package now, so I think I can add you to the repo as maintainer and give publisher permissions on NPM to make things easier

**Comment by carlosjeurissen** [comment]
Closed by #5
